package com.fr.hailian.rtxWebservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-11T15:09:24.691+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://www.nwh.cn/Rpc", name = "IMServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface IMServiceSoap {

    @WebMethod(operationName = "SendIMMessageToUser", action = "http://www.nwh.cn/Rpc/SendIMMessageToUser")
    @RequestWrapper(localName = "SendIMMessageToUser", targetNamespace = "http://www.nwh.cn/Rpc", className = "com.fr.hailian.rtxWebservice.SendIMMessageToUser")
    @ResponseWrapper(localName = "SendIMMessageToUserResponse", targetNamespace = "http://www.nwh.cn/Rpc", className = "com.fr.hailian.rtxWebservice.SendIMMessageToUserResponse")
    @WebResult(name = "SendIMMessageToUserResult", targetNamespace = "http://www.nwh.cn/Rpc")
    public java.lang.String sendIMMessageToUser(
        @WebParam(name = "TaskTitle", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String taskTitle,
        @WebParam(name = "MsgContent", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String msgContent,
        @WebParam(name = "TransUrl", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String transUrl,
        @WebParam(name = "UserName", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String userName,
        @WebParam(name = "UserList", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String userList,
        @WebParam(name = "From", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String from,
        @WebParam(name = "BusinessId", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String businessId,
        @WebParam(name = "Rank", targetNamespace = "http://www.nwh.cn/Rpc")
        int rank
    );

    @WebMethod(operationName = "CancelMessage", action = "http://www.nwh.cn/Rpc/CancelMessage")
    @RequestWrapper(localName = "CancelMessage", targetNamespace = "http://www.nwh.cn/Rpc", className = "com.fr.hailian.rtxWebservice.CancelMessage")
    @ResponseWrapper(localName = "CancelMessageResponse", targetNamespace = "http://www.nwh.cn/Rpc", className = "com.fr.hailian.rtxWebservice.CancelMessageResponse")
    @WebResult(name = "CancelMessageResult", targetNamespace = "http://www.nwh.cn/Rpc")
    public java.lang.String cancelMessage(
        @WebParam(name = "BusinessId", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String businessId,
        @WebParam(name = "From", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String from,
        @WebParam(name = "UserList", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String userList
    );

    @WebMethod(operationName = "SendMessageToUser", action = "http://www.nwh.cn/Rpc/SendMessageToUser")
    @RequestWrapper(localName = "SendMessageToUser", targetNamespace = "http://www.nwh.cn/Rpc", className = "com.fr.hailian.rtxWebservice.SendMessageToUser")
    @ResponseWrapper(localName = "SendMessageToUserResponse", targetNamespace = "http://www.nwh.cn/Rpc", className = "com.fr.hailian.rtxWebservice.SendMessageToUserResponse")
    @WebResult(name = "SendMessageToUserResult", targetNamespace = "http://www.nwh.cn/Rpc")
    public java.lang.String sendMessageToUser(
        @WebParam(name = "TaskTitle", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String taskTitle,
        @WebParam(name = "MsgContent", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String msgContent,
        @WebParam(name = "TransUrl", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String transUrl,
        @WebParam(name = "UserName", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String userName,
        @WebParam(name = "UserList", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String userList,
        @WebParam(name = "From", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String from,
        @WebParam(name = "SMSType", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String smsType,
        @WebParam(name = "SendSMSTime", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String sendSMSTime,
        @WebParam(name = "BusinessId", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String businessId,
        @WebParam(name = "Rank", targetNamespace = "http://www.nwh.cn/Rpc")
        int rank
    );

    @WebMethod(operationName = "SendSMSMessageToUser", action = "http://www.nwh.cn/Rpc/SendSMSMessageToUser")
    @RequestWrapper(localName = "SendSMSMessageToUser", targetNamespace = "http://www.nwh.cn/Rpc", className = "com.fr.hailian.rtxWebservice.SendSMSMessageToUser")
    @ResponseWrapper(localName = "SendSMSMessageToUserResponse", targetNamespace = "http://www.nwh.cn/Rpc", className = "com.fr.hailian.rtxWebservice.SendSMSMessageToUserResponse")
    @WebResult(name = "SendSMSMessageToUserResult", targetNamespace = "http://www.nwh.cn/Rpc")
    public java.lang.String sendSMSMessageToUser(
        @WebParam(name = "sendSMSTime", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String sendSMSTime,
        @WebParam(name = "MsgContent", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String msgContent,
        @WebParam(name = "TransUrl", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String transUrl,
        @WebParam(name = "UserName", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String userName,
        @WebParam(name = "DesList", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String desList,
        @WebParam(name = "From", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String from
    );
}
