
package com.fr.hailian.rtxWebService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-11T15:09:24.669+08:00
 * Generated source version: 3.1.12
 * 
 */
public final class IMServiceSoap_IMServiceSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://www.nwh.cn/Rpc", "IMService");

    private IMServiceSoap_IMServiceSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = IMService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        IMService ss = new IMService(wsdlURL, SERVICE_NAME);
        IMServiceSoap port = ss.getIMServiceSoap12();  
        
        {
        System.out.println("Invoking sendIMMessageToUser...");
        java.lang.String _sendIMMessageToUser_taskTitle = "";
        java.lang.String _sendIMMessageToUser_msgContent = "";
        java.lang.String _sendIMMessageToUser_transUrl = "";
        java.lang.String _sendIMMessageToUser_userName = "";
        java.lang.String _sendIMMessageToUser_userList = "";
        java.lang.String _sendIMMessageToUser_from = "";
        java.lang.String _sendIMMessageToUser_businessId = "";
        int _sendIMMessageToUser_rank = 0;
        java.lang.String _sendIMMessageToUser__return = port.sendIMMessageToUser(_sendIMMessageToUser_taskTitle, _sendIMMessageToUser_msgContent, _sendIMMessageToUser_transUrl, _sendIMMessageToUser_userName, _sendIMMessageToUser_userList, _sendIMMessageToUser_from, _sendIMMessageToUser_businessId, _sendIMMessageToUser_rank);
        System.out.println("sendIMMessageToUser.result=" + _sendIMMessageToUser__return);


        }
        {
        System.out.println("Invoking cancelMessage...");
        java.lang.String _cancelMessage_businessId = "";
        java.lang.String _cancelMessage_from = "";
        java.lang.String _cancelMessage_userList = "";
        java.lang.String _cancelMessage__return = port.cancelMessage(_cancelMessage_businessId, _cancelMessage_from, _cancelMessage_userList);
        System.out.println("cancelMessage.result=" + _cancelMessage__return);


        }
        {
        System.out.println("Invoking sendMessageToUser...");
        java.lang.String _sendMessageToUser_taskTitle = "";
        java.lang.String _sendMessageToUser_msgContent = "";
        java.lang.String _sendMessageToUser_transUrl = "";
        java.lang.String _sendMessageToUser_userName = "";
        java.lang.String _sendMessageToUser_userList = "";
        java.lang.String _sendMessageToUser_from = "";
        java.lang.String _sendMessageToUser_smsType = "";
        java.lang.String _sendMessageToUser_sendSMSTime = "";
        java.lang.String _sendMessageToUser_businessId = "";
        int _sendMessageToUser_rank = 0;
        java.lang.String _sendMessageToUser__return = port.sendMessageToUser(_sendMessageToUser_taskTitle, _sendMessageToUser_msgContent, _sendMessageToUser_transUrl, _sendMessageToUser_userName, _sendMessageToUser_userList, _sendMessageToUser_from, _sendMessageToUser_smsType, _sendMessageToUser_sendSMSTime, _sendMessageToUser_businessId, _sendMessageToUser_rank);
        System.out.println("sendMessageToUser.result=" + _sendMessageToUser__return);


        }
        {
        System.out.println("Invoking sendSMSMessageToUser...");
        java.lang.String _sendSMSMessageToUser_sendSMSTime = "";
        java.lang.String _sendSMSMessageToUser_msgContent = "";
        java.lang.String _sendSMSMessageToUser_transUrl = "";
        java.lang.String _sendSMSMessageToUser_userName = "";
        java.lang.String _sendSMSMessageToUser_desList = "";
        java.lang.String _sendSMSMessageToUser_from = "";
        java.lang.String _sendSMSMessageToUser__return = port.sendSMSMessageToUser(_sendSMSMessageToUser_sendSMSTime, _sendSMSMessageToUser_msgContent, _sendSMSMessageToUser_transUrl, _sendSMSMessageToUser_userName, _sendSMSMessageToUser_desList, _sendSMSMessageToUser_from);
        System.out.println("sendSMSMessageToUser.result=" + _sendSMSMessageToUser__return);


        }

        System.exit(0);
    }

}
